Repository shrawani21/gamer_21, pull requests merged in 2024-06, with the labels that each got.

#113 Adding learn.md for user convenience
  LEARN.md
Labels: gssoc, level2

#108 Added Tech Stack Used.md
  README.md
Labels: documentation, gssoc, level1

#119 Create LICENSE
  LICENSE
Labels: documentation, gssoc, level2

#111 Add Replay and Quit buttons in the existing game
  main.py
Labels: gssoc, level2
